# ================================================
# Task Configuration File
# ================================================
# Define task groups for easy selection

### Tasks by Objective ### 

QA_TASKS=(
    "MedQA"
    "MedMCQA"
    "TrialPanorama_Arm_Design"
    "TrialPanorama_Eligibility_Criteria_Design"
    "TrialPanorama_Endpoint_Design"
    "TrialPanorama_Evidence_Summarization"
)

NLI_TASKS=(
    "MedNLI"
    "PubMedQA"
    "Evidence_Inference_v2"
    "NLI4PR"
    "HINT"
    "Trial_Meta_Analysis_type"
    "Trial_Meta_Analysis_binary"
    "Trial_Meta_Analysis_continuous"
    "TREC_CDS_balanced"
    "TREC_Prec_Med_balanced"
    "TREC_CT_balanced"
    "SemEval_NLI4CT"
    "TrialBench_adverse_event_prediction"
    "TrialBench_mortality_rate_prediction"
    "TrialBench_patient_dropout_prediction"
    "TrialBench_trial_approval_prediction"
    "TrialBench_trial_failure_reason_identification"
    "TrialBench_trial_duration_prediction"
    "TrialPanorama_Study_Screening"
)

IE_TASKS=(
    "Trial_Meta_Analysis_type"
    "Trial_Meta_Analysis_binary"
    "Trial_Meta_Analysis_continuous"
)

ES_TASKS=(
    "RCT_Summary"
)

RANKING_TASKS=(
    "TREC_CDS"
    "TREC_CDS_balanced"
    "TREC_Prec_Med"
    "TREC_Prec_Med_balanced"
    "TREC_CT"
    "TREC_CT_balanced"
)

### Tasks by Dataset ###

TRIALBENCH_TASKS=(
    "TrialBench_adverse_event_prediction"
    "TrialBench_mortality_rate_prediction"
    "TrialBench_patient_dropout_prediction"
    "TrialBench_trial_approval_prediction"
    "TrialBench_trial_failure_reason_identification"
    "TrialBench_trial_duration_prediction"
)

TRIALPANORAMA_TASKS=(
    "TrialPanorama_Arm_Design"
    "TrialPanorama_Eligibility_Criteria_Design"
    "TrialPanorama_Evidence_Summarization"
    "TrialPanorama_Endpoint_Design"
    "TrialPanorama_Study_Screening"
)

TREC_TASKS=(
    "TREC_CDS"
    "TREC_CDS_balanced"
    "TREC_Prec_Med"
    "TREC_Prec_Med_balanced"
    "TREC_CT"
    "TREC_CT_balanced"
)

### Tasks by Useful Groups ###

SMALL_TASKS=(
    "MedNLI"
    "MedQA"
    "PubMedQA"
    "NLI4PR"
)

# All Tasks
ALL_TASKS=(
    "${QA_TASKS[@]}"
    "${NLI_TASKS[@]}"
    "${IE_TASKS[@]}"
    "${ES_TASKS[@]}"
    "${RANKING_TASKS[@]}"
)

# Export arrays
export QA_TASKS NLI_TASKS IE_TASKS ES_TASKS RANKING_TASKS
export TRIALBENCH_TASKS TRIALPANORAMA_TASKS TREC_TASKS SMALL_TASKS ALL_TASKS